AICC/CMI-5_Spec_Current

cmi5_runtime.md
launchMethod changes and various other corrections.
=> Launch method changes

cmi5_coursestructure.md
Added Course Package (section 8), updated launchMethod, and minor changes from meeting minutes through January 16, 2015.
=> Meeting minutes through 1/16/2015

cmi5_runtime.md
=> Restore LMS Obligations in 9.3.6

cmi5_runtime.md
Changes to section 9.6 from meeting minutes March 27, 2015
=> Change to 9.6 per minutes

cmi5_runtime.md
=> Remove suspended and removed verbs

cmi5_runtime.md
=> Duration calculation for abandoned

cmi5_coursestructure.md, cmi5_runtime.md
* Removed references to OAuth
* noted we may add other authentication options in the future
* removed redundant course structure information from the runtime document
=> Removed OAuth

cmi5_runtime.md
=> Add satisfied verb

cmi5_coursestructure.md, cmi5_runtime.md
also removed some redundant "MUST" statements
=> Added passIsFinal setting

README.md
Adding editorial fixes for README.md
=> Editorial fixes - README.md

cmi5_coursestructure.md
Added the capability to extend the course structure as requested by @MrBillMcDonald in issue #161 
The following example demonstrates the capabilites:
https://github.com/svrnm/CMI5-CourseStructure-Testing/blob/master/extension/cmi5.xml
=> Course Structure Extensions

cmi5_coursestructure.md
=> Changed license for course structure

cmi5_runtime.md
=> PR for "Initialized verb should be a MUST"

cmi5_runtime.md
This is the third pull request solving issue #149
=> Replaced CMI-5 with cmi5 in cmi5_runtime.md

cmi5_runtime.md
=> Replaced "Learning Activity" with "AU" in runtime specification

cmi5_coursestructure.md, cmi5_runtime.md
Sandstone updates of revision history.
=> Editorial Fixes - Revision History

cmi5_coursestructure.md, cmi5_runtime.md
Added disclaimer to both docs.
=> Added disclaimer

cmi5_coursestructure.md
Missing carriage return. Fixed.
=> editorial fixes - acronyms

cmi5_runtime.md
=> editorial fixes - lms conformance

cmi5_coursestructure.md, cmi5_runtime.md
The LMS Requirements differed between documents. I made them match.
=> Editorial fixes - lms requirements

cmi5_runtime.md
=> editorial fixes - 7.2 - runtime

cmi5_runtime.md
This looks like a lot, but it's really just table formatting.
=> editorial fixes - 10.0 - runtime

cmi5_coursestructure.md, cmi5_runtime.md
=> Remove redundant "system" in "lms system"

cmi5_coursestructure.md
Changed 'an parameter' to 'a parameter'.
=> Fixed typo

cmi5_coursestructure.md, cmi5_runtime.md
As discussed today I merged both lists of contributors and added @jamie-burns who contributed two PRs today.
=> Combined both contributor lists

cmi5_runtime.md
Don't allow voiding statements
=> Changes discussed in issue 202

cmi5_runtime.md
Per August 7th Meeting :
* Replace remaining "Actor object" terminology with "Actor property" terminology.
* Add IRI for Progress definition
=> Actor property updates per Aug 7 Mtg.

cmi5_coursestructure.md
As discussed (#225, #214) I created a simple and a complex course structure example and added both to the end of the specification. I validated both examples using the current XSD.
=> Added course structure examples to specification

cmi5_runtime.md
Add Language for Optional JSON Values (section 4.3) per August 28th Meeting.
=> Add Language for Optional JSON Values

cmi5_runtime.md
Add Error Value descriptions for fetch URL errors (in section 8.2.3.2) per August 28th Meeting
=> Add Error Value descriptions

cmi5_coursestructure.md
=> Fixed inverted lang strings in example

cmi5_coursestructure.md
I added some changes to the section about extensions (here: Vendor Specific Metadata). Mainly the things i suggested here: #215
=> Additions to "Vendor Specific Metadata"

cmi5_runtime.md
As far as I remeber we agreed on the name "course designer" instead of "AU designer"
=> AU designer -> course designer

cmi5_coursestructure.md
Remove the Bibliography and update references with  MIME per the Sept 11 meeting
=> Remove the Bibliography and update references

cmi5_runtime.md
Remove Bibliography - Update references (move MIME reference).  Per Sept 11 meeting
=> Remove Bibliography - Update references

cmi5_spec
As per discussion in Sep 11 meeting.  Prepare to create at unified specification
=> Add runtime to combined spec (initial draft)

cmi5_spec.md
Starting with runtime as base document for merge.  Changes will be added from course structure to merge the two documents.
=> Starting with runtime as base document for merge

cmi5_spec.md
Proposal to combine Runtime and Course Structure into one spec per September 11th meeting.
=> Combine Runtime and Course Structure into one spec

cmi5_spec.md
correct "completion" property in example/  Per issue #261
=> correct "completion" property in example

cmi5_spec.md
=> Add cmi5 Logo to title

cmi5_spec.md
=>   Including a reference to the XML definition

README.md
Just a bunch of fixes for the readme: added links, fixed some markdown errors, ...
=> Minor fixes for the readme

cmi5_spec.md
Remove passIsFinal from examples (2nd pull to remove passIsFinal due to editor problems)
=> Remove passIsFinal from examples

cmi5_spec.md
The following PR adds missing sections into the table of contents and fixes some document references.
=> Added missing entries in table of contents

cmi5_spec.md
=> Removed Web Browser Environments

cmi5_spec.md
This shouldn't change any requirements, etc. but generally improve the overall state of the document. It may be easier to look at individual commits since they are intentionally subdivided, with the "Editing pass" being the most "controversial" though even it shouldn't really be. For the formatting issues it may be easiest to look at the document under my GitHub fork to see what the final product is.
=> Various Document Fixes

cmi5_spec.md
=> Minor fixes

cmi5_spec.md
* Drop possessive "id's" and suggestion statements have multiple verbs
* Quote Initialized/Terminated verb
Addresses #332
=> Switch 'content template' to 'context template'

cmi5_spec.md
=> Remove default value from `activityType`

cmi5_spec.md
=> Update "endpoint" to not mention "auth" value

cmi5_spec.md
* Matches what is already done for AU and Block (particularly since
there is an "<objectives>" element)
=> "Objectives" -> "Objective" for Metadata

cmi5_spec.md
=> Update Section 9.1

cmi5_spec.md
=> Update Section 9.3.8 Terminated

cmi5_spec.md
=> Update Section 8.2.2

cmi5_spec.md
=> Section 9.5.4.2

cmi5_spec.md
Changes to address Issue #309 (agreed in Nov 20 meeting)
=> Changes for Issue #309 (Nov 20 meeting)

cmi5_spec.md
References were to old course structure document.
=> Fixed incorrect references in 9.3.9

cmi5_spec.md
Per 12/4 call, resolves issue #315.
=> Remove unnecessary description of Activity

cmi5_spec.md
=> Note example launch URL not encoded

cmi5_spec.md
Addresses #322, and one place for #336 (adjusts one sample URL to use "example.com" and be a little more generic).
=> "CMI5" -> "cmi5"

cmi5_spec.md
=> Improve language for "contextTemplate"

cmi5_spec.md
Addresses #336. (Leaves one which will get resolved as part of #369.)
=> Switch to example.com for remaining sample URLs

cmi5_spec.md
=> Remove "authenticationMethod" from AU metadata

cmi5_spec.md
Another feature of w3id is that they use https
=> Replaced all PURL IRIs with W3ID IRIs

cmi5_spec.md
Per Jan 15th meeting (and Issue #297) update timestamp defintion
=> Update TimeStamp Definition (per Issue #297) 

cmi5_spec.md
Correct references to section 7.1.4 AU Meta data (Should be 13.1.4)
=> Correct references to 13.1.4

cmi5_spec.md
Issue #305 - Repeated Course Structure Requirements
Wording agreed to in Dec 4th Meeting.
=> Issue #305 - Repeated Course Structure Requirements

cmi5_spec.md
Issue:  #345 - .Zip Application Note
Add to ZIP specification to references per Jan 29th, 2016 Meeting
=> For Issue:  #345 - .Zip Application Note

cmi5_spec.md
=> Indicate AU id must be unique in course structure

cmi5_spec.md
=> Remove "Abandoned" from list of statements setting result.completion

README.md
- Fix typo in LinkedIn Group URL
=> Fix LinkedIn Group URL

cmi5_spec.md
=> Update masteryScore precision

cmi5_spec.md
To address Issue #392 - "Waived" uses session language what does that look like?
Agreed per Feb 26th, 2016 Meeting.
=> For Issue #392 - "Waived" Session language

cmi5_spec.md
To correct Issue :
complex cmi5.xml example has invalid locale #416
(Unless this for the Pennsylvania Deutsch / Amish !)
=> Issue #416 Pennsylvania Deutsch

cmi5_spec.md
Since we have the concept of a "course" be specific about wording and use "AU".
=> Clarify AU rather than course for exit procedure

cmi5_spec.md
Fix duplicate locale for au  http://example.com/courses/f59c9fc0/au/6f66
=> Issue #415 - Fix duplicate locale

cmi5_spec.md
Resolves issue #394 - Is "Satisfied" recorded for AU's with a "NotApplicable" "moveOn"?
Per March 25th Meeting
=> For issue #394

cmi5_spec.md
Changes to address
Issue #389 - Meaning of progress when it differs between statements
Agreed per the March 11, 2016 Meeting
=> For Issue #389

cmi5_spec.md
=> http -> https for reason extension

cmi5_spec.md
=> SHOULD not issue multiple satisfied statements

cmi5_spec.md
=> Indicate launchParameters are a string

cmi5_spec.md
=> Improve language around objectType for object property

cmi5_spec.md
Revise 9.4 to remove 9.4.1 and 9.4.2.  Change 9.4 per meeting minutes April 22, 2016.
=> Revise 9.4 per issue #434 

cmi5_spec.md
LMS MUST remove leading and trailing white space for elements upon course import.
=> Address issue #446

cmi5_spec.md
Indicate LaunchMethod is not required attribute, and add default value of "AnyWindow".   Addresses issue #444.
=> Address issue #444

cmi5_spec.md
Indicate that Satisfied statement targets Block or Course, not AU.
=> Address issue #450

cmi5_spec.md
Changes to masteryScore, launchParameters and moveOn in State per meeting minutes May 6, 2016.
=> Resolve issues #424 and #425

cmi5_spec.md
Include launchURL in context of Launched statement
=> Resolve issue #447

v1/examples/complex-cmi5.xml, v1/examples/extended-cmi5.xml, v1/examples/simple-cmi5.xml
=> Correct XML schema namespace in course examples

cmi5_spec.md
Resolve issue #443 - Satisfied session id in case of NotApplicable moveOn
=> Resolve issue #443

cmi5_spec.md
Address changes from issue #449 - Can Waived contain a Score?
=> Resolve issue #449

cmi5_spec.md
Resolve issue #454 - 8.1 endpoint
=> Resolve issue #454

cmi5_spec.md
add  Dennis Hall to list of contributors
=> add  Dennis Hall to list of contributors

cmi5_spec.md
Adding the best practice samples as previously identified are (hopefully obviously) not included. I'm working on them.
=> Remove sample JSON blocks

cmi5_spec.md
Per May 27th Meeting
This pull request to resolve Issue #452 - We need to define termination here
=> To Resolve Issue #452

cmi5_spec.md
This pull request includes the spec changes agreed for issue #473.  Since the remaining part of #473 does not include changes to the spec, Quartz can be released without complete resolution of #473.
=> Changes per issue #473

cmi5_spec.md
Remove redundant requirements, Update LRS Retrieval and Display Requirement.
=> Resolve issues #484 and #451
