cmi5_coursestructure.md

Hi,
this pull request contains all changes discussed during the last two meetings:
- Elements like id, moveOn, etc. are converted to attributes
- Objectives are centralized and referenced by au or block
- The XSD is reflecting these changes and also contains some other fixes like ```<langstring>```
Regards,
Severin

Attributes, Centralized Objectives, Working XSD, etc.

---

cmi5_coursestructure.md

As discussed in  #116 the following patch includes an optional activity type attribute to the course structure.

Added activityType as attribute

---

cmi5_coursestructure.md

The html in the AU metadata documentation had some wrong placed tags. This caused some errors like missing description texts etc.

Fixed HTML table in course structure

---

README.md

Just a minor change request: Since the this repository (=AICC/CMI-5_Spec_Current) is forked quiet often and maybe will be forked more often I think referencing the correct base repository in the README.md file will make sure, that people create their issues and pull requests for the correct repository.
Of course, if the repository is moved to another organization this link has to be updated.

Add repository reference to README

---

cmi5_coursestructure.md

The given patch makes the use of langstring an requirement. For me this seems to be the correct interpretation of the specification. So this makes the following illegal:
```xml
<course id="...">
<title>This is a title</title>
<description>Wer hätte gedacht, dass die Beschreibung auf Deutsch ist?!</description>
</course>
```
The modification only allows the following:
```xml
<course id="...">
<title>
<langstring lang="en-US">This is a title</langstring>
</title>
<description>
<langstring lang="de-DE">Wer hätte gedacht, dass die Beschreibung auf Deutsch ist?!</langstring>
</description>
</course>
```
The disadvantage of this change might be, that people will nevertheless skip the ```<langstring>``` because they are used to it...
**Remark**: The given example shows that it is possible to …

Using langstring is an requirement

---

cmi5_coursestructure.md

As discussed in the [April 10th meeting](https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-April-10th,-2015) I have added the element ```<languages>``` to the course structure. This allows to write the following:
```xml
<course id="course">
<title>...</title>
<description>...</description>
<languages>en-US es-MX</languages>
</course>
```
I slightly modified the notation: I renamed the element from "language" to "languages" and I fixed the listing from named elements (```<en-US>```, ```<es-MX>```) to space separated strings.

Added languages element to course structure

---

cmi5_coursestructure.md

Currently the most simple course structure requires an entitlementKey and launchParameters. As far as I understand the runtime and course structure specification both can be optional or at least have an empty value, so a explicit specification in the cmi5.xml is not required.

Make entitlementKey and launchParameters optional

---

cmi5_coursestructure.md

The following pull request is an suggestion as well as a question, if I'm understanding the meaning of this element correctly:
Suggestion: The course structure specification had a "TBD" for the ```<launchParameters>``` example value, so I added a possible xample.
Question: The added example is a json string. My understanding of a discussion during one of our meetings was, that the launch parameters can be used to provide some generic kind of configuration. By "generic" I mean that the course designer can choose any format he likes, e.g. some proprietary text format (KK3;XD;T_0) or some existing format (json, xml(?!), yaml, ...). Is this assumption correct?

Example value for launchParameters

---

README.md

I created a singular pull(*) request that changes all occurrences of "CMI-5" with "cmi5" in the README.md. This partially solves issue #149 
---
(*) Anticipating that large PRs may be not mergeable.

Replaced CMI-5 with cmi5 in README.md

---

cmi5_coursestructure.md

Like #167 this is a singular pull request that renames "CMI-5" to "cmi5" within the course structure. This partially solves #149

Replaced "CMI-5" to "cmi5" in cmi5_coursestructure.md

---

cmi5_runtime.md

There were still two "AU designer" in the runtime specification. See #153

Replaced "AU designer" with "course designer" in cmi5_runtime.md

---

cmi5_coursestructure.md

The namespace of the xml schema still contains the aicc.org. This PR replaces **aicc.org/CMI5** with **www.adlnet.gov/cmi5**

Changed xml namespace of schema (aicc -> adl)

---

cmi5_coursestructure.md

Changed the description of the Mastery Score from Required to Optional.
Also removed the reference to an empty string, since this can be
achieved by omitting the attribute from the element instead.  The
description should now match the XSD.

Made Mastery Score optional

---

cmi5_coursestructure.md

This is an minor issue: There were two ```&lt;``` instead of ```&gt;``` within an example, cmp. changed file

Fixed wrong tagging

---

cmi5_runtime.md

Its changed in other places but looks like it was left out here in Section 7.2.1

changed extension sessionid to url

---

cmi5_runtime.md

Remove remaining references to oAuth (and statements that indicate that there is an alternative form of authentication) in the cmi5 runtime specification.  
Per Issue #235.

Remove remaining oAuth references (Per Issue #235.)

---

cmi5_runtime.md

Clarify rules for Abandoned verb.  LMS must not allow additional statements to be recorded after an "Abandoned" is issued.

Clarify rules for Abandoned verb (per issue #236)

---

cmi5_runtime.md

The "completed" property was missing from the example json in section 9.5

Completed property missing from result

---

cmi5_runtime.md

(Issue#237) - RFC 2396 vs RFC 3986 vs RFC 3987
The cmi spec incorrectly refers to URI when it should reference the IRI specification (RFC 3987). 
Per August 28th Meeting.

Replace URI RFC reference with IRI RFC

---

cmi5_coursestructure.md

A third example using a fictitious set of vendor specific metadata (i.e. extension)

Course structure example using an extension

---

cmi5_coursestructure.md

The specification doesn't explicitly define where the XML file should be located within a ZIP file.

Location of the course structure XML within a ZIP

---

cmi5_coursestructure.md

Same change as in the runtime specification

URI changed to IRI at course structure spec

---

cmi5_runtime.md

Added Timestamp requirement (in UTC timezone) for all cmi5 statements per the Sept 11 meeting

Added Timestamp/UTC requirement

---

cmi5_spec.md

In Section 13.1.1. the RFC 3987 is referenced once, this is redundant.

Removed inline reference to RFC 3987  in 13.1.1

---

cmi5_spec.md

The levels of conformance (must, should, may, (need not)) are defined twice at the sections "Definition" and "Conformance". I assume that the first one can be removed?

MUST, SHOULD, MAY removed from definitions

---

README.md

A "mailto:" does not require the slashes. And I assume that the "+" should be spaces (%20)

Fixed Slack Request Link

---

cmi5_spec.md

Per CMI 5 Working Group Meeting Minutes – September 18th, 2015 (issue #262 and #263)
As part of the discussion on issues 262/263, the issue of how the LMS should deal with statements that conflict with cmi5 spec rules came up.
The group agreed that the following rules should be added to cmi5 spec to clarify what the LMS should/must do:
1. LMS SHOULD reject statements that conflict with the spec.
2. Any statement that conflicts with the cmi5 specification rules that is NOT rejected MUST be voided by the LMS.

Add rejection/voiding rules for LMS

---

cmi5_spec.md

Remove "passIsFinal" feature from the course structure definition/XSD and from verb rules.
(Removal of "passIsFinal" from XML examples pending due to editor issues)

Remove passIsFinal

---

cmi5_spec.md

The fetch URL must always be a URL.

Fix value space for fetch in 8.1.1

---

cmi5_spec.md

Also removes trailing '.' from "None" to be consistent with the most common approach in this section.
Resolves #343.

Set LMS obligations to 'None' for "Initialized"

---

cmi5_spec.md

Updates to consistently use 'authorization token' rather than 'authentication token'.

'authentication token' -> 'authorization token'

---

cmi5_spec.md

I'm not sure I love the wording of the requirements here yet, but I wanted to take a first stab and get it out there for discussion.
This PR makes it so that when issuing a "passed" or "failed" statement based on comparison of a learner's score with the "masteryScore" that "masteryScore" is provided in the context as an extension. Currently there is no way for a statement processor to know what the mastery score was that was used to determine the pass/fail result, only that it had such result. This is particularly important since the "masteryScore" can be passed dynamically to the AU through the launch data.

Add masteryScore as context extension

---

cmi5_spec.md

Remove tabs, switch to non-enumerated bullets, and switch 'are' to 'as'.

Markdown fixes

---

cmi5_spec.md

Addresses #303. The link should be maintained as the xAPI specification moves, I'd expect at least one more time prior to this doc's release at 1.0.3.

Set version of xAPI specification to 1.0.x

---

cmi5_spec.md

Addresses #304 based on discussion from 12/4.

Remove unnecessary language from IRI definition

---

cmi5_spec.md

Addresses #318. Tried to be as consistent as possible with the language already existing in "launchParameters".

Improvements to "masteryScore" and "moveOn" in LaunchData section

---

cmi5_spec.md

Addresses #324.
There are a couple of places still using "message" because they are "transport mechanism" agnostic, in the conceptual model section.

Switch to use "request" instead of "message"

---

cmi5_spec.md

Addresses #326, #327 and #328.
No need to mention "masteryScore" inclusion in LMS launch data under verb listing. Sets LMS obligations to none for failed verb statements. Removes redundant and insufficient language around multiple statement inclusion covered elsewhere.

Fix items related to "passed" and "failed" verb statements

---

cmi5_spec.md

* Correct which verbs can include "success" (remove Abandoned)
* Correct which verbs can include "completion" (remove Failed)
* Make JSON example conformant for possible inclusion
Addresses #330 and #331.
The example JSON wasn't conformant because there is no way to record a single statement with both `success: false` and `completion: false`. (Also it'd likely be bad form to have a progress of 100% but not completed, though I suppose it is possible (unless that's an issue onto itself?))

Items related to Result objects

---

cmi5_spec.md

Make it so that requirements on the LMS for handling "Terminated" and "Abandoned" are only in their respective locations.

Remove redundancy in "Terminated" and "Abandoned"

---

cmi5_spec.md

* Switches "progress" extension to use the table format
Fixes #314.
Because the "progress" extension was not previously in table format I used the text from the opening of the section as the description and AU usage values, these should be checked, as should the LMS cells which are just set as "None" at the moment.

Moves "reason" extension to Result object

---

cmi5_spec.md

Fixes reversion of change to w3id.org ids caused by the merge of #365.

Correct w3id for reason that slipped in from other merge

---

cmi5_spec.md

Fixes #358.
*But* I'm concerned that this wording is too loose and doesn't capture whether or not you *must* always provide 3 decimal places, unless that is implied by "precision". IOW, do I have to provide `1.000` when `1` will do?

Indicate precision of masteryScore

---

cmi5_spec.md

Issue #378 - Explicitly allow the LMS to override the "masteryScore" as defined in the course structure
(Section 6.1 only)  Per January 29th, 2016 Meeting  (The rest of issue #378 is not resolved yet)

For-Issue #378-section-6.1-only

---

cmi5_spec.md

To address Issue #388 - masteryScore is missing from example json in 9.6
Agreed Per Feb 26th, 2016 meeting

For Issue #388

---

cmi5_spec.md

To address issue:  #378 - Explicitly allow the LMS to override the "masteryScore" as defined in the course structure
Per March 25th Meeting,

For Issue #378 - Activity ID Management

---

cmi5_spec.md

This is related to the changes made in #421 (the inclusion of "publisherid") and is in the 'object' section for statements. The 'object.id' property is the one now generated by the LMS and is therefore no longer related to the course structure.

object.id no longer directly related to course structure

---

cmi5_spec.md

Start to address issue #408. I chose what I considered "sane" values for the block and course activity type, but I don't really have ownership to coin terms in w3id.org/xapi so someone, presumably Jason Haag or the working group should make final decision on the terms. We should also get the metadata created.

Add requirement for Definition.type for Satisfied

---

cmi5_spec.md

* Break context activities description into sub-sections
* Remove publisher id as a context template extension
* Add publisher id Activity as part of context activities 'grouping' list
Fixes issue #431.
The changes include some language change around the xAPI concepts that are being used, specifically it changes the language to indicate that the things going in contextActivities are in fact Activities (they must be per xAPI spec) and that they are going in a specific list (which is the value of the property from the xAPI spec) within that object indicated by a specific property of the object.
I also adjusted the use of language indicating that they can be used as a "wildcard search" mechanism as that really isn't the case. There isn't any facility for say searching for an Activity id of …

Switch publisher id handling

---

cmi5_spec.md

Per April 15, 2016 meeting:
1) Passed and Completed are registration specific.  (only one completed & passed per registration allowed)
2) Failed may not follow Passed

Address issue #434

---

cmi5_spec.md

Section 9.6 Context - to explicitly say that the LMS must use a context template in the statements it creates. (all cmi5 defined statements require a context template)

Address issue #455
